# Generated by Django 5.2.9 on 2025-12-27 14:56

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomtype',
            name='amenities',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='is_smoking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='view_type',
            field=models.CharField(choices=[('CITY', 'City View'), ('SEA', 'Sea View'), ('GARDEN', 'Garden View'), ('POOL', 'Pool View')], default='CITY', max_length=20),
        ),
        migrations.AlterField(
            model_name='property',
            name='city',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
