# Generated by Django 5.2.9 on 2025-12-27 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_roomtype_amenities_roomtype_is_smoking_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomtype',
            name='capacity',
            field=models.PositiveIntegerField(help_text='Max people allowed'),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='name',
            field=models.CharField(choices=[('SINGLE', 'Single Room'), ('DOUBLE', 'Double Room'), ('TWIN', 'Twin Room'), ('STUDIO', 'Studio'), ('DELUXE', 'Deluxe Suite'), ('FAMILY', 'Family Suite'), ('PRESIDENTIAL', 'Presidential Suite')], default='SINGLE', max_length=50),
        ),
    ]
