# Generated by Django 5.2.9 on 2025-12-27 15:36

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_roomtype_capacity_alter_roomtype_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('day_of_week', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), blank=True, help_text='0=Monday, 6=Sunday', null=True, size=None)),
                ('price_multiplier', models.DecimalField(decimal_places=2, default=1.0, help_text='Standard, 1.2 = +20%, 0.8 = -20%', max_digits=4)),
                ('room_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='priding_rules', to='inventory.roomtype')),
            ],
        ),
    ]
