# Generated by Django 5.2.9 on 2025-12-27 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_pricingrule'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pricingrule',
            old_name='day_of_week',
            new_name='days_of_week',
        ),
    ]
