# Generated by Django 5.2.9 on 2025-12-27 16:19

import autoslug.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_rename_day_of_week_pricingrule_days_of_week'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomtype',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, default='', editable=False, populate_from='name', unique=True),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='RoomImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='room_images/')),
                ('is_cover', models.BooleanField(default=False, help_text='Is this the main image shown in search?')),
                ('caption', models.CharField(blank=True, max_length=100)),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='inventory.roomtype')),
            ],
        ),
    ]
