# Generated by Django 5.2.9 on 2025-12-30 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_roomtype_slug_roomimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
