# Generated by Django 5.2.9 on 2025-12-27 01:31

from django.db import migrations
from django.contrib.postgres.operations import BtreeGistExtension


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        BtreeGistExtension(),
    ]
