# Generated by Django 5.2.9 on 2025-12-29 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_booking_canceled_at_booking_is_refunded_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='stripe_payment_intent_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
