# Generated by Django 5.2.9 on 2025-12-29 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_booking_stripe_payment_intent_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='canceled_at',
            new_name='cancelled_at',
        ),
    ]
