# Generated by Django 5.2.9 on 2025-12-30 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_rename_canceled_at_booking_cancelled_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Canceled'), ('EXPIRED', 'Expired')], default='PENDING', max_length=20),
        ),
    ]
