# Generated by Django 5.2.9 on 2025-12-31 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_alter_booking_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
